### ISSUE TITLE
[BUG]FileNotFoundError: [Errno 2] No such file or directory: 'ubpf jit'

### ISSUE THREAD

**Issue by codoerrrrrrrrrrrrrrr** [eunomia-bpf/bpf-benchmark#1]
Hello, running the run_benchmark. py script to start the benchmark test shows FileNotFoundError: [Errno 2] No such file or directory: 'ubpf jit'. Is it because the executable file is not compatible with the system? My system version is 6.5.0-25 generic. Thank you for your reply

**Comment by Officeyutong** [comment]
Could provide a more detailed stack trace?

**Comment by codoerrrrrrrrrrrrrrr** [comment]
```console
TESTS
--------------
memory_a_plus_b
strcmp_full
prime
log2_int
switch
simple
memcpy
strcmp_fail
--------------
Loaded 8 tests
Testing ubpf-jit
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/liujie/bpf-benchmark/run_benchmark.py", line 70, in run_multiple_wrapper
    r = run_single(**cfg)
  File "/home/liujie/bpf-benchmark/run_benchmark.py", line 49, in run_single
    ret = subprocess.run(command_line, text=True, capture_output=True, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ubpf-jit'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/liujie/bpf-benchmark/run_benchmark.py", line 180, in <module>
    main()
  File "/home/liujie/bpf-benchmark/run_benchmark.py", line 126, in main
    results = pool.map(
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'ubpf-jit'
```

**Comment by codoerrrrrrrrrrrrrrr** [comment]
> Could provide a more detailed stack trace?是否可以提供更详细的堆栈跟踪？

TESTS
--------------
memory_a_plus_b
strcmp_full
prime
log2_int
switch
simple
memcpy
strcmp_fail
--------------
Loaded 8 tests
Testing ubpf-jit
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/liujie/bpf-benchmark/run_benchmark.py", line 70, in run_multiple_wrapper
    r = run_single(**cfg)
  File "/home/liujie/bpf-benchmark/run_benchmark.py", line 49, in run_single
    ret = subprocess.run(command_line, text=True, capture_output=True, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ubpf-jit'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/liujie/bpf-benchmark/run_benchmark.py", line 180, in <module>
    main()
  File "/home/liujie/bpf-benchmark/run_benchmark.py", line 126, in main
    results = pool.map(
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'ubpf-jit'

**Comment by Officeyutong** [comment]
It's my fault, I forget to update the executable list. I'll fix it

**Comment by codoerrrrrrrrrrrrrrr** [comment]
> It's my fault, I forget to update the executable list. I'll fix it是我的错，我忘了更新可执行列表。我会把它修好

Thank you very much.

**Comment by codoerrrrrrrrrrrrrrr** [comment]
> It's my fault, I forget to update the executable list. I'll fix it这是我的错，我忘记更新可执行文件列表。我会修复它

Did you fix it? I'm still getting errors.

**Comment by Officeyutong** [comment]
> > It's my fault, I forget to update the executable list. I'll fix it这是我的错，我忘记更新可执行文件列表。我会修复它
> 
> Did you fix it? I'm still getting errors.

I'm sorry i'm too busy these days. I've already updated, so you may try again now

**Comment by yunwei37** [comment]
The maintainer fixed the executable list after this report, and the current repository no longer contains the old `run_benchmark.py` / `ubpf-jit` invocation path that produced this `FileNotFoundError` (the names now only appear in historical/reference docs). Closing this old framework bug as resolved/obsolete.
